### PR TITLE
Add SVGs

### PR DESCRIPTION
**Pull request by ikocevski**
- MiXplorer - com_mixplorer_com_mixplorer_activities_BrowseActivity

### CODE REVIEW

**Comment by ikocevski** [comment]
I took the time to understand git and committed this one through it. Yay!

**Comment by dkanada** [comment]
Nice, git is a very useful tool once you figure it out, just takes a bit of work. The **/other** folder works for now.

**Comment by ikocevski** [comment]
And now the pull says "Add MiXplorer SVG" when there are 2 svgs to add :/ Still getting the hang of git I guess...

**Comment by conrad-heimbold** [comment]
@ikocevski: 
one tip for git from me: **commit often** (for most steps), **branch / pull only** if **big steps** of work have been done.

**Comment by dkanada** [comment]
I am going to merge this to add that new icon so I don't forget about it when I am adding converted icons.

**Comment by dkanada** [comment]
Shoot didn't realize there were three new icons, do you have component names for the other two?

**Comment by ikocevski** [comment]
Master Password - com_lyndir_masterpassword_com_lyndir_masterpassword_EmergencyActivity
Camera Roll - us_koller_cameraroll_us_koller_cameraroll_ui_MainActivity

I put these in the comments of the commits or whatever the three dots serve for here on GitHub. Thought you'd notice, but here they are anyway.

**Comment by dkanada** [comment]
Just added the three new icons from this pull request.

**Pull request merged**
