### PR TITLE
Convert old png icons

### PR DESCRIPTION
**Pull request by ikocevski**
You can leave this open for a bit.. just to know which icons are already done ;)

### CODE REVIEW

**Comment by ikocevski** [comment]
Okay, you can pull these now and I'll just let you guys finish the rest. 10 more to go!

**Comment by conrad-heimbold** [comment]
Could you also delete the finished png ones with your pull request?

**Comment by dkanada** [comment]
@conrad-heimbold I can remove the old icons, and I will also be doing the first five icons of the ten that are left. Let me know if you need me to do the other five as well.

**Comment by conrad-heimbold** [comment]
I've only done radiodroid so far

**Comment by dkanada** [comment]
Did the rest, throw up a pull request with the last icon and then we will finally be done. That was a huge project, thanks for the help guys.

**Comment by conrad-heimbold** [comment]
>... and then we will finally be done. 

Next step would probably be to use android vector XML instead of png's, fixing issue #26. I wouldn't say our work is done. Using android vector XML would make our app 
- **uniquely small** (in terms of size of the apk)
- **uniquely customizable** (you could probably change icon colors/opacity inside the app!) and 
- **uniquely sharp** (because the icons can be scaled better than just rasterized images)
...**among all other icon packs**

**Comment by ikocevski** [comment]
@dkanada No worries man, always glad to contribute for the FOSS community. Thank *you* for reviving this project.

**Pull request merged**
