### PR TITLE
add new svg icons

### PR DESCRIPTION
**Pull request by conrad-heimbold**
Added icons for the following... 

System apps with launchable foreground activities:  
- Bluetooth Extension - ``org.codeaurora.bluetooth/
  org.coreaurora.bluetooth.ftp.BluetoothFtpActivity``
- Bluetooth Share - ``com.android.bluetooth/
  com.android.bluetooth.opp.BluetoothOppLauncherActivity``

System service apps **without launchable foreground activities**:  
- AntHALService - ``com.dsi.ant.server``
- CMServiceAudio - ``org.cyanogenmod.cmaudio.service``
- CMServiceThemes - ``org.cyanogenmod.themeservice``
- CMServiceLiveLockscreen - ``org.cyanogenmod.livelockscreen.service``
- CMServiceWeather - ``org.cyanogenmod.weatherservice``

These system services do appear in the app list in settings and they can crash. So having an extra icon in these cases is worth it, IMHO. 

Normal apps: 
- ApplicationsInfo - ``com.majeur.applicationsinfo/ 
  com.majeur.applicationsinfo.MainActivity``
- Urbandroid (please choose one version) - ``com.urbandroid.sleep/ 
  com.urbandroid.sleep.alarmclock.AlarmClock``

### CODE REVIEW

**Comment by dkanada** [comment]
I am leaving this one open for now.

**Comment by dkanada** [comment]
@ikocevski @conrad-heimbold It is very time consuming for me to add all the components to appfilter.xml so could you guys add those for any new apps you add? I have scripts for drawable.xml and icon_pack.xml so I can manage those. You can find the format in either of the app filter files in the project, on is in the resources directory and the other is in todo. @conrad-heimbold I reformatted the app filter in todo so it matched the main file, that should make copying entries over much easier. I can also release a new version now, do you want me to wait for the app filter entries for this PR or just release one as soon as I can?

**Comment by conrad-heimbold** [comment]
@dkanada Don't wait for this pull request , release a new app version now, I would say.

**Comment by conrad-heimbold** [comment]
@dkanada I will ```$ git reset --hard ...``` this branch from me and change the commits, so that 
- only apps with activity names are included
- the new metadata is directly added to /app/res/XML/appfilter.xml

**Comment by ikocevski** [comment]
@dkanada Alright, the next time I add an icon I will also edit the appfilter.xml. Do tell if you think I should do anything else.

And I know it's offtopic but how much time does it take for the update to go online on F-Droid? It's been what, three days now?

**Comment by conrad-heimbold** [comment]
@ikocevski F-Droid Server seems to have a lot of issues and seems to be quite unmaintained. Better build the app yourself

**Pull request closed without merging**
