### PR TITLE
All new and shiny readme + new icons

### PR DESCRIPTION
**Pull request by ikocevski**

### CODE REVIEW

**Comment by conrad-heimbold** [comment]
@ikocevski : do you think including some of my tips from issue #30 would be a good idea? I copy-pasted them here: 

### How to contribute: 

- If you want to directly contribute more than just two or three icons (or even contribute some code to other projects), I suggest you to learn how to use git (a programm)
- if you only want to contribute two or three icons, then posting the svgs as uploaded file, or in a gist ( https://gist.github.com ) should be enough, no need to learn git. 

## How to style the svgs
- ideal size of the svg would be **048x048** pixel. 
- if it's not that size: no problem, we can scale other sizes up or down to 48x48 px
- the templates for svg files can be found in **/templates**. If your icon will have a **square, rectangular or circle shape**; please use one of these templates
- try not to use **"transform"** attributes inside the svgs. 
Unfortunately, Inkscape **often** adds those without consent. 
In that case: 
> #### How to remove transforms in Inkscape
> - Open svg file in Inkscape
> - Go to Edit -> XML Editor (or press CTRL SHIFT X )
> - Find "transform"  attributes in layers and delete them
> #### How to move all objects altogether without creating another transform attributes
> - Go to Edit -> Select All in All Layers (or press CTRL A)
> - Go to Object -> Transform
> #### In Transform panel
> - Uncheck Relative move and check Apply to each object separately
> - Set Horizontal and Vertical values according to your needs and
> - click Apply

## My personal prefered way of styling svgs in Inkscape / tips and tricks
- I am working in 48x48 px documents
- I always make the icon grid visible in inkscape by pressing "#" or View → show icon grid
- I always try to make the icon **fit into the grid as good as possible**.  This will make the icon **more sharp** if exported to png. 
- I use **guide lines** heavily. You can transform a normal line (or multiple lines of a form) into a guide line by pressing SHIFT+G. points can be placed more easily, because they **snap** to those guiding lines / to intersections of guiding lines / to intersections of guiding lines and icon grid. 

You don't have to respect my personal preferred way of styling svgs


If you are not working in Inkscape, I can't help very much unfortunately...

**Comment by ikocevski** [comment]
I actually thought about these points when I was editing the readme but it's just too much text. Someone looking at the readme would be like TLDR and leave. Maybe we could make a reference/link to this with something like more detailed guide [here]?

**Comment by conrad-heimbold** [comment]
Ok, here is a short version of my tips & tricks (for inkscape): 
- **use 48x48 pixel** icons. Other sizes are ok, but we will have to scale up or down (more work for us)
- **use the templates** from /templates , if your icon will have a **square / circle / rectangular shape**. 
- Only during work: For **changing the background color or enabling checkerboard background layout** (to see especially **white icons on white background**), change File -> Document Properties -> Background Color or enable Checkerboard Layout in there. 
- one tip from me: use **guide lines** heavily. Points can **snap** (if enabled on the right) to these guide lines / to intersections of guide lines (making the point / edge locations more **precise**). You can transform a normal line (or multiple lines of a form) into a guide line by Object -> Transform into Guide Line (SHIFT+G)
- one more tip from me: I also use the **background grid** (getting visible by **pressing #**) heavily for snapping and orientation. I always try to make the icon **fit into the grid as good as possible**.  This will make the icon **more sharp if exported to png**/ the svg file **smaller in size and complexity**. 
- At one point in the future, we would like to use Android **vector drawables instead of pngs**. Unfortunately, android vector drawables **do not support matrix / transform** elements, **fill-rule:evenodd attributes** and the scientific **E-notation** (used for really small numbers, e.g. 5e-3 = 0.005 ), at least not before Android API level 24. Try not to use these svg features! To check this, just open the svg file (it should be a simple text file), and search for the mentioned strings. 

## How to get rid of matrix / transform elements in Inkscape
For some of these possibilities, you might need to remove the matrix/transform attributes before. To do this, go to Edit -> XML Editor (CTRL+SHIFT+X) and **delete all matrix / transform attributes**. 
### Possibility 1: 
combine one of the matrix / transform objects with another one (select them, then CTRL+PLUS ). 
- Advantage: always works, 
- Disadvantage: You loose some special editing functionality (e.g. no more rounded corners for rect's)
### Possibility 2: 
- problem: if multiple objects are combined into a group, and you only select this group when moving objects, the group will get a transform attribute. 
- solution: 1. Un-group the objects (SHIFT+G), 2. Move the objects one-by-one OR select multiple ones by keeping SHIFT pressed during selection and movement of them. 3. Group them again. 
### Possibility 3: 
- When moving objects the next time, do **not** do it with your keyboard / manually, but **use the transform window in Inkscape**: 
1. Select all objects you would like to move (e.g. CTRL+A)
2. Go to Object -> Transform (CTRL+SHIFT+M)
3. Uncheck "Relative Move" and check "Apply to each object separately".
4. Specify the horizontal and vertical values for movement. 
5. Click Apply. 

## How to get rid of fill-rule:evenodd attributes
So far, I could always just delete this attribute - the icon never looked different. Please check that in your case. 

## How to get rid of E-notation
In our case, E-notation should only be used for really small numbers. They can usually be replaced by just 0 (zero). Inkscape often does rounding errors, which pile up. Please check that in your case.

**Comment by conrad-heimbold** [comment]
@ikocevski: maybe we can split away the **HOW-TO** part from my text into a separate file named HOWTO.md?

**Comment by ikocevski** [comment]
Yes, I was just about to say that LOL

**Comment by ikocevski** [comment]
Why don't you just make that HOWTO file, make a pull request and I'll just make a link to it in the readme. That'd be great.

**Comment by conrad-heimbold** [comment]
yep, i'll do that

**Comment by ikocevski** [comment]
@dkanada You can see what I changed and how I work but if you don't have time..

I first add a new SVG in **/other** then add that app's activity in appfilter.xml *and* proceed removing the app activity lines from **/todo/new** appfilter.xml and finally remove the png from **/todo/new**. Is this OK?

Also now that we've converted the old pngs maybe we don't need the **/todo/new **folder? Maybe just /todo is good enough? I don't know, won't make that change, just consider it as a suggestion ;)

**Comment by dkanada** [comment]
@ikocevski yeah those steps are perfect, thanks. I thought I had already removed the new folder, I will remove it now.

**Comment by dkanada** [comment]
It looks like I did remove the new folder at some point, maybe run another git pull to see if yours is removed.

**Comment by ikocevski** [comment]
Hm.. that's odd, either my brain glitched which is most probable or git glitched. Anyway.. why did we suddenly slow down adding icons? Come on keep the tempo :D

**Comment by dkanada** [comment]
I am working on lots of other projects that I bounce between haha, I was pushing all those icons because I wanted to get this app to a more complete state but I also have a bunch of other stuff to do. I want to add more functionality to another app of mine called OpenAPK and I also wanted to fork GBA.emu and see if I could get a new build working for F-Droid. I definitely have more icons to add to this app and I also want to work on the codebase but I do all my work in blocks depending on which project I think needs more work.

**Comment by ikocevski** [comment]
Yeah, keep up the good work, the world needs it :) I'll still be here to add some more.

I also started a new language pack for AnySoftKeyboard. Might slow down too, just might though.

**Comment by conrad-heimbold** [comment]
I slowed down because
- I gave other people help how to make svg's, so now they could take over (see HOWTO)
- I am working on using android vector drawables inside the app instead of png's. For that, I am also working on a similar project ( conrad-heimbold/SimpleTwoColorVectorIcons )
- I have got more important stuff to do.

**Comment by conrad-heimbold** [comment]
BTW: I think git treats empty directories as "not existing". I noticed that behaviour especially for freshly created empty directories, IDK if it's different for directories that contained files **in the past**.

**Pull request merged**
