### PR TITLE
new icons in original mono-colors. 

### PR DESCRIPTION
**Pull request by conrad-heimbold**
@dkanada : Please choose one of the chefkoch icons and delete the other ones. chefkoch.1... is sharper (because it fits better onto the pixel grid for small icon sizes), but looks unnatural; chefkoch.2... looks more like the original chefkoch icon (but is blurred). 

I hope, I typed in everything correctly...

Could you do the svg-white-converting?

### CODE REVIEW

**Comment by dkanada** [comment]
I can convert them to white, I am also thinking of adding a square and circular template for new icons because a few of the ones I have added are incorrectly sized, what do you think? Maybe I could also add a portrait and landscape rectangle to the templates, not sure how useful those would be though. Also, do you want to stick with 32x32 or 192x192 as the size? I don't have a preference either way but I will be changing all the svgs to the same size at some point.

**Comment by conrad-heimbold** [comment]
I would prefer 32x32 as svg icon size over 192x192, because upscaling is better than downscaling. 


Upscaling means exporting e.g. a 128x128 px png icon from a 32x32 px svg. 
Downscaling means exporting e.g. a 128x128 px png icon from a 192x192 px svg. 

Downscaling makes png icons blurred and not sharp, as you can imagine. 
Upscaling is only better (sharper), if you pay attention to one thing: 
edges and corners should fit as good as possible into the pixel grid. 
In Inkscape, you can see the pixel grid by pressing "#". 


So when creating the 32x32 px icon templates, please pay attention that e.g. the rectangular shapes have got an integer (NOT rational!) pixel distance to the surrounding (e.g. 3px, 10px, ...; NOT 3.20473 or 10.4444 ).

**Comment by conrad-heimbold** [comment]
Most icon sizes are integer multiples of 32:
- 64 = 2 x 32
- 96 = 3 x 32
- 128 = 4 x 32
- 192 = 6 x32
- 256 = 8 x 32
- 512 = 16 x 32

Some are rational multiples of 32:
- 48 = 1.5 x 32 = 3 x 16
- 72 = 2.25 x 32 = 4.5 x 16
- 144 = 4.5 x 32 = 9 x 16

Maybe we should even use 16x16 svg px templates? 

I can only say: 192 is not a good idea.

**Comment by dkanada** [comment]
Working on switching the icons to 32x32 now, do you mind if I just remove the colors in this repository? I can't really do anything with them anyways and it would make the icons easier to maintain.

**Comment by conrad-heimbold** [comment]
ok, delete the colors.

**Comment by conrad-heimbold** [comment]
Could we maybe keep the colors as 
hex code - file name combo 
in a file named styles.css? 
I could maintain that file.

**Comment by dkanada** [comment]
Just added one in other folder, I made it an xml since it's an android project but it can be css as well, just change it when you add the icons you want.

**Pull request merged**
