### PR TITLE
add svg icons; bug fixes; add data and png icon requests; rename those icons, etc.

### PR DESCRIPTION
**Pull request by conrad-heimbold**

### CODE REVIEW

**Comment by conrad-heimbold** [comment]
the last 6 commits only happened inside /todo/new .

**Comment by dkanada** [comment]
Android doesn't like dashes in the icon names so we have to rename any icons with dashes currently in them.

**Comment by conrad-heimbold** [comment]
Can we use underscore (_)?

**Comment by dkanada** [comment]
Yeah that'll work.

**Pull request merged**
