### PR TITLE
new icons in original colors

### PR DESCRIPTION
**Pull request by conrad-heimbold**
- The svg icons have got the size 32x32px . I chose this size, because for some smartphones, this is the minimum icon size (AFAIK). If you don't like that, you should be able to scale them automatically with 
```
inkscape --export-width=192 --export-height=192 --export-plain-svg 
```

- The svg icons are in original color. If you want to change the color to white; just search for the string "#" plus HEX code in all the files inside "in_original_colors" and replace all occurences with #FFFFFF automatically. 
- the svg icons do not always consist only of one path/object. I can change that if wanted. This has to be done manually....
- a lot of "id"s and "class"es can probably be deleted automatically with scour. 
If this is too much work for you, I can of course improve my pull request.

### CODE REVIEW

**Comment by dkanada** [comment]
Thanks for the new icons! I have only been saving them as 192x192 because Turtl saves icons in that size, it just removes a step when creating new svg files. I added a separate directory if you want to add colored ones there, I will add two versions from now on if you use the colored icons. I should add a script for that eventually.

No worries about having multiple paths for the svg files, they actually seem easier to edit when the objects are separated. I will probably clean up the files with svgo tomorrow and change the sizes so they are all the same.

**Comment by dkanada** [comment]
I am going to remove the edge icons, most of the icons in the rest of the pack have rounded edges and I don't really want to keep more than one drawable for each icon unless they have totally different designs or something. I am also going to shrink a few of the icons so there is a bit of padding between the objects and the edge of the canvas to standardize the sizes. I am going to keep working on adding icons over time, feel free to submit more pull requests if you want to add more icons or other ideas for the app.

**Comment by conrad-heimbold** [comment]
removing the edge icons is ok for me. 
I just had them to "track" changes on the icons.

**Comment by conrad-heimbold** [comment]
BTW: sometimes, there are two versions of the same icon. 
You can delete the one which you don't like as much. 
One is always more oriented towards the ICEcon pngs; the other one more oriented towards the original icon. I couldn't decide which one to choose...

**Comment by dkanada** [comment]
Alright cool, I just added a script to convert the colored icons so we could keep them as well.

**Comment by dkanada** [comment]
Is there an easy way to mirror an object across the canvas? I have been using hacks to do it but I am hoping there is a tool or something I missed.

**Comment by conrad-heimbold** [comment]
In Inkscape, I always do: 
Object > Horizontal inverting 
or
Object > Vertical invert

You should also be able to do that by typing "H" or "V".

**Comment by conrad-heimbold** [comment]
If you want to mirror it across the diagonal (going from the bottom left to the top right), you can also just interchange x- and y-coordinates to achieve mirroring.

**Comment by dkanada** [comment]
I meant take an object on one side of the canvas and mirror it across the center of the canvas to the other side, it would make my life easier when icons have gaps between objects or symmetric shapes. An example would be the two headphones in the timber icon or the four squares in the calculator icon.

**Comment by conrad-heimbold** [comment]
Sorry, I could not find / do not know such a functionality. 
I always do copy & paste; and change the position of the copied object manually. 
But I am also just Inkscape beginner. 
Maybe there is an add-on for that?

**Comment by conrad-heimbold** [comment]
I use the help grid extensively and try to position the points as often as possible on intersections of this grid. You can enable it with "#".  This makes mirroring / calculating much easier.

**Comment by dkanada** [comment]
I will try the grid again, I was using it a while ago but it didn't seem very accurate at centering things, just correctly spacing objects.

**Comment by dkanada** [comment]
I was working on adding in the new icons but I need apps to pair them with if they aren't already in the icon pack as png files, can you use turtl to get the required information for the new icons?

**Comment by conrad-heimbold** [comment]
[20170519_032715.zip](https://github.com/dkanada/ICEcons/files/1013140/20170519_032715.zip)

**Pull request merged**
