### PR TITLE
fix appfilter for 16 apps

### PR DESCRIPTION
**Pull request by conrad-heimbold**

### CODE REVIEW

**Comment by dkanada** [comment]
What do you think about shifting the goal of this project? See my conversation [here](https://github.com/beli3ver/Paper-FOSS-Theme/issues/19#issuecomment-319359119) about trying to get more graphic designers creating icon packs for F-Droid. Maybe we could focus solely on icons for apps on F-Droid and provide a complete appfilter for every app in the official repos. @ikocevski let me know what you think as well.

**Comment by conrad-heimbold** [comment]
@dkanada
- Every icon pack developer and user has a **different taste concerning colors and shapes** of the icons
- Every FOSS icon pack tries to make icons **for all apps in F-Droid**, so all FOSS icon pack developers are **working on basically the same appfilter file**, but they **don't share their appfilter metadata**. Instead, we are doing **unnecessary** "double" work. 

One of the big disadvantages of git is: you **can't download single files** (e.g. the appfilter file) from a remote repo (at least not on github!); you always have to clone the **complete** remote repo.

 If you only need the appfilter data (for your own icon pack), but **not** all the icons (because you want to style them differently), you still have to download everything, stressing bandwidth and storage space. 

Conclusion: Having a "meta" repo that contains both svg icons for all FOSS app icons **and** includes appfilter metadata for all FOSS apps is **no good idea**. **BUT** having those in two **different** repos would be **really useful**!!

**Comment by ikocevski** [comment]
I agree the the appfilter should work as an API for icon packs, no more manually adding every value to every repository but only one. Now, how would that work... it should be mergeable to **all** icon pack repos, so it should be one file in the repo (just appfilter.xml) ?

That's definitely doable.

Now for the SVG icons, I think the developers of FOSS apps should upload their **original icon** in a vector format (preferably plain SVG) in order to help icon pack makers. I have no idea how we'd reach out to all of them but this would be fantastic. Otherwise I think having a repo with SVGs that are not from the app developer is pointless. Every icon pack has it's own style as @dkanada said.

Instead, having a repo where graphic designers could easily just add SVGs they make, merge the appfilter list and get a finished icon pack app would be really attractive.

**Comment by conrad-heimbold** [comment]
@ikocevski 
In git, you can add another complete git repo (e.g. the appfilter repo) as sub-folder. That's called **submodule**.

**Comment by ikocevski** [comment]
@conrad-heimbold 
Hm... yes, but the repo will still be ICEcons/something, right? Why not make a new repo with a new name that will be more recognizable? And I could take a guess and say it's going to be easier not to work with these submodules.

Anyway, the question is, do we have the biggest and most up-to-date appfilter list here on ICEcons?

**Comment by dkanada** [comment]
We probably have a decent list of F-Droid apps in our appfilter but I have no clue if we have the largest. It should work fine for now, although once I figure out the best way to structure the split repos we will be heavily modifying the appfilter. I still think that switching this project to only apps from F-Droid would be a good move. We would also have to include the default apps for stock android and custom roms of course, otherwise many icons would be missing.

**Comment by dkanada** [comment]
What do you guys think of only including icons for F-Droid apps? We would have to remove some apps that are already included but we would keep the google suite and apps included by default on any system like cameras and galleries. Although the g-suite is not on F-Droid most people do not ever remove those apps from their phone which is why I would leave the icons. I will miss a few icons but it will be a lot easier to decide which apps we add icons for and maintain the appfilter. @conrad-heimbold @ikocevski

**Comment by conrad-heimbold** [comment]
@dkanada That's definitely a good idea. 
I am working on a script that 
1. parses the metadata for all apps on F-Droid, by downloading it from https://gitlab.com/fdroid/fdroiddata/tree/master/metadata , reading the $APP_NAME, $SOURCE_URL, $SUBDIR, $REPO_TYPE
2. Downloads the AndroidManifest.xml **and** the highest-quality original png icon for every app on F-Droid by using the mentioned $SOURCE_URL , $SUBDIR and $REPO_TYPE data from before
3. Extract the $PACKAGE_NAME and $MAIN_ACTIVITY_NAME from the AndroidManifest.xml file; give the png icon a suitable name by parsing the $APP_NAME and attach all necessary information to the appfilter file

In the end, getting the necessary information for the appfilter.xml file should be completely automated, requring as little human interaction as possible.

**Comment by ikocevski** [comment]
@dkanada The way I look at it, it's a downgdrade and it's probably the way everyone will see this when they no longer have the icons that were there. Many Samsung phones nowadays come with Microsoft apps pre-installed (Skype, Word, Excel, PowerPoint, Outlook and even Cortana) and you can't delete them because they're system apps. How should we handle that?

If we look at it this way, it's outright bad. BUT, since people get ICEcons from F-Droid (it's the only way) I can bet these people fall into that niche audience that use **only** FOSS apps (such as myself). Now when you look at it this way it's just fine to make this change. *Unless* we don't include other FOSS apps that are not available on F-Droid (ex. Camera Roll), then I'd be disappointed.

**Pull request merged**
