### PR TITLE
clean up todo-list for new icons; add 6 (7) system and 4 normal app icons; remove matrix/transform elements ( issue #27 )

### PR DESCRIPTION
**Pull request by conrad-heimbold**
Added icons for the following... 

System apps with launchable foreground activities (commits fed3baf , 6ba245a , 9106370 ):  
- Bluetooth Extension - ``org.codeaurora.bluetooth/
  org.coreaurora.bluetooth.ftp.BluetoothFtpActivity``
- Bluetooth Share - ``com.android.bluetooth/
  com.android.bluetooth.opp.BluetoothOppLauncherActivity``

System service apps **without launchable foreground activities** (commits fed3baf , 6ba245a , 9106370 ):  
- AntHALService - ``com.dsi.ant.server``
- CMServiceAudio - ``org.cyanogenmod.cmaudio.service``
- CMServiceThemes - ``org.cyanogenmod.themeservice``
- CMServiceLiveLockscreen - ``org.cyanogenmod.livelockscreen.service``
- CMServiceWeather - ``org.cyanogenmod.weatherservice``

These system services do appear in the app list in settings and they can crash. So having an extra icon in these cases is worth it, IMHO. 

Normal apps (commits  2387ae4 , e26cca7 , 53f1300 , 3dc80e4 , ca54d4f  ): 
- ApplicationsInfo - ``com.majeur.applicationsinfo/ 
  com.majeur.applicationsinfo.MainActivity``
- FreeYourGadget - ``nodomain.freeyourgadget.gadgetbridge/
  nodomain.freeyourgadget.gadgetbridge.activities.ControlCenterv2`` 
- QRForKeepass - ``keepass2android.plugin.qr/ 
  keepass2android.plugin.qr.MainActivity``
- Urbandroid (please choose one version) - ``com.urbandroid.sleep/ 
  com.urbandroid.sleep.alarmclock.AlarmClock``

### CODE REVIEW

**Comment by conrad-heimbold** [comment]
The last five commits  ( d1fc944 , 65624d0 , dadf600 , 05598aa , ceb043a )  removed the matrix / transform attributes from these icons, addressing issue #27

**Comment by conrad-heimbold** [comment]
@dkanada : If you don't like all of my work, you can also **cherry-pick** only specific commits with git

**Comment by conrad-heimbold** [comment]
The commits containing "todo-list", which are: 
f2a1a23 , 833ab89 , f822502 , 4aa68c8 , 12d1de5 , c6d2ffd , 370a155 , 7bab90b , 4b3bd8c , ca8f86d , 52ad801 , b69e4c8 , 8e64731 , 2f35840 , ab0434c , a90346c , 6434b9f , 938087c , 25c58da , 88010ee , , 92d96ff , b7c40a1 , e2ef28e , 91d8386 , df3ab13 , 43a231d , b3a2f55
... only deleted finished icons and/or the respective lines from appfilter.xml inside /todo/new/ .

**Comment by dkanada** [comment]
Your work is always totally fine, I am holding off on adding new icons until I finish the last 70 icons in **/todo/old** though, it will make things easier.

**Comment by dkanada** [comment]
Also, is there any chance you can modify the app filter for new icons and use two lines per item again with four spaces of indentation?

**Comment by conrad-heimbold** [comment]
> Also, is there any chance you can modify the app filter for new icons and use two lines per item again 
> with four spaces of indentation?

Yeah, no problem.

**Comment by conrad-heimbold** [comment]
I split this pull request into multiple ones: #35, #34, #33 . Therefore, I could close it.

**Pull request closed without merging**
