### PR TITLE
Convert icons

### PR DESCRIPTION
**Pull request by ikocevski**

### CODE REVIEW

**Comment by dkanada** [comment]
I am going to leave this open for a bit so you don't have to add more pull requests when you add new icons. At some point in the future I will also turn this project into an organization and give you guys write access so we don't need to worry about pull requests anymore.

**Comment by ikocevski** [comment]
Alright.. and wow that's great news!

**Comment by ikocevski** [comment]
Guys, is it OK to make the icons more detailed like I just did with DDG or the whole point of the icon pack is to go minimal (previous DDG icon) ? Waiting for your answer so I know what to do with the next icons I make.

**Comment by dkanada** [comment]
Normally a bit of detail is fine but the eyebrows and center of the bow will not scale well at all. I also generally try and keep the icons simple when I can so the beak is a bit oddly shaped in my opinion, so for this icon I would stick with the old design.

**Comment by dkanada** [comment]
Also just in case you ever want to use the scripts, here is an explanation for their uses.

raster.sh
- adds the png files to the app folder
- runs scour with some custom parameters to clean the svgs
- moves the svgs from other to icons

scour.sh
- only runs scour on the svgs

todo.sh
- soon to be deprecated
- checks the app folder for old icons that haven't been implemented yet

white.sh
- @conrad-heimbold sometimes submits icons in color
- converts icon color to white in svgs

xml.sh
- generates drawable.xml and iconpack.xml for the app folder
- creates a file to be copied over to IconActivity for icon previews

**Comment by ikocevski** [comment]
Damn I spent too much time making this icon perfect.. now I'll have to redo it, can I just remove the eyes and eyebrows? I have the original file for editing (I use layers).
Also, what is scour? When I installed Inkscape I got an optional dependency for it and it said something like optimized SVG. When I save the final icons for uploading here I choose Optimized SVG instead of Inkscape SVG. Isn't this the same thing?

**Comment by dkanada** [comment]
Just removing the eyebrows should be fine, and scour is a tool that formats svg files and shrinks the filesize, it is available on Linux but I am not sure about Windows, not sure what you are using at the moment. No clue what optimized svg is but it probably does something similar.

**Comment by ikocevski** [comment]
https://www.archlinux.org/packages/extra/any/python2-scour/
Source code: https://github.com/scour-project/scour
That's the optional dependency but I don't know much about it, can't seem to find any info about it online or if it's in any way connected with the "Optimized SVG" option in the Save menu.
Anyway I'll remove the eyebrows and recommit this one.

**Comment by conrad-heimbold** [comment]
@ikocevski   Here is a slightly more complicated duckduckgo icon as png: 
duckduckgo2 

Maybe you can make use of it.

**Comment by ikocevski** [comment]
@conrad-heimbold I used the original full color image to make mine so, yeah but thanks. The only thing that's missing from my icon is the other part of the tie, but I can do that too if you want.

**Comment by conrad-heimbold** [comment]
no no thanks, it's perfect the way it is.

**Comment by ikocevski** [comment]
@conrad-heimbold Alright, uhm btw how do you save your files in Inkscape?

**Comment by conrad-heimbold** [comment]
The raw versions and finished versions are not online (because sometimes, there are really messed up), I only upload the optimized ones.

**Comment by ikocevski** [comment]
Yeah, I upload only the optimized ones but why run the same script again it's double work...

**Comment by conrad-heimbold** [comment]
Somehow, I think, the optim window in Inkscape does not offer all of the functionality of the script. E.g. 
--remove-descriptive-elements is not supported, AFAIK, in the save dialog. I think there's even more.

**Comment by ikocevski** [comment]
So, I should save in Inkscape SVG, run the scour script provided and then commit the resulting SVG, is that right?

**Comment by conrad-heimbold** [comment]
You can also commit with "normal" SVG or Inkscape SVG; the scour script online in /other/scour.sh (once your pull request has been merged, it will be executed by dkanada) should do the work (AFAIK).

**Comment by ikocevski** [comment]
Turns out after I ran that script I actually got more bits than the original file (with Inkscape's scour/Optimized SVG). What now? @dkanada Thoughts?

**Comment by conrad-heimbold** [comment]
If you are not sure, why one version of scour produces different results than another, just inspect the svg files and the scour.sh script. I think you can find out :)

**Comment by dkanada** [comment]
Yeah you can always inspect the text. I pushed a [commit](https://github.com/dkanada/ICEcons/commit/cce9914aed8659fb7288d042dceee04d068de159) yesterday where I ran scour on a couple of icons, you can see the differences there.

**Comment by ikocevski** [comment]
Yeah, just use your script it's fine...
I added the Firefox icons:
firefox1 = old style with more detail
firefox1-alt = old style with a bit less detail (notice at the left side, less fur)
firefox2 = a bit different, going a bit out of the template size for the fox
firefox2-alt = same as above but less detail

Hope you like them ;)

**Comment by ikocevski** [comment]
@dkanada Can you pull this now and remove the icons from todo? 7 done if I counted right.

**Comment by conrad-heimbold** [comment]
@ikocevski I never dared to do/finish the Firefox icon - it always looked ugly... Yours however looks really good!

**Comment by conrad-heimbold** [comment]
@ikocevski : for firefox2.svg and firefox2-alt.svg , the margin I marked 
firefox2 svg

... would be very small for icons in 48x48 / 128x128 px size. Could you maybe make it bigger?

**Comment by ikocevski** [comment]
Thanks, I had me some major help from the official svg I found online but still took me a while to make it right. I always search for these before I make the icon and sometimes get lucky 😀

**Comment by ikocevski** [comment]
Yeah, I could do that but tomorrow.

**Comment by ikocevski** [comment]
@conrad-heimbold Okay, updated the firefox2 icons they were also not centered, oops :S

**Comment by ikocevski** [comment]
What a mess.. Updated them and they're all perfect now... but the choice I must admit is tough :D

**Comment by dkanada** [comment]
Yeah sure, merging now.

**Pull request merged**
