### PR TITLE
delete finished icons from list for new todo app icons (see also my other pull requests)

### PR DESCRIPTION
**Pull request by conrad-heimbold**

### CODE REVIEW

**Comment by dkanada** [comment]
Why close this? I don't think I have added any of the changes yet.

**Comment by conrad-heimbold** [comment]
I thought we should focus on the old icons

**Comment by dkanada** [comment]
Yeah that's what I have been working on, no reason to close a useful pull request though, pretty sure all the component names you removed were added at some point. I was just waiting on finishing up the old icons before I merged this one and the other one with some new icons.

**Comment by conrad-heimbold** [comment]
@dkanada : You didn't seem to be interested (no comment from you), that's why. Whatever you wish

**Comment by dkanada** [comment]
Ah okay, sorry about that I was just putting it on hold.

**Comment by conrad-heimbold** [comment]
>... and then we will finally be done. 

Next step would probably be to use android vector XML instead of png's, fixing issue #26. I wouldn't say our work is done. Using android vector XML would make our app 
- **uniquely small** (in terms of size of the apk)
- **uniquely customizable** (you could probably change icon colors/opacity inside the app!) and 
- **uniquely sharp** (because the icons can be scaled better than just rasterized images)
...**among all other icon packs**

**Pull request merged**
