### PR TITLE
add some icons

### PR DESCRIPTION
**Pull request by conrad-heimbold**

### CODE REVIEW

**Comment by conrad-heimbold** [comment]
Funny, we've been working on the same icon (forkhub) :)

**Comment by dkanada** [comment]
Just added the icons, went with you version of forkhub.

**Comment by dkanada** [comment]
I just realized that removing the height and width fields in the svg files means github will render them at a larger size. I can actually see the changes to icons on github now!

**Comment by conrad-heimbold** [comment]
AFAIK, scour removed width and height attributes. That wasn't intended by me

**Comment by dkanada** [comment]
Yeah, I switched to scour recently so all of my icons still had those fields. Could you add new icon files to other instead of icons? The script copies svg files from there and also automatically runs scour, works like a charm.

**Pull request merged**
