### PR TITLE
sort icons by sizes in DIRs for easier working

### PR DESCRIPTION
**Pull request by conrad-heimbold**
in the long run, we would like to have all svg icons in 048x048 size. 
To get a better overview, having all icons in the applicable dir makes things much easier.

### CODE REVIEW

**Comment by dkanada** [comment]
Thanks, I am going to go with 48x48 since google uses that for system icons. I added the templates, those are also following the [material design guidelines](https://material.io/guidelines/style/icons.html) for icons. Odd shapes should have eight pixels of padding between the icon and the edge of the canvas.

**Comment by conrad-heimbold** [comment]
How to convert dpi in px? Does dpi basically mean px in our case?

**Comment by dkanada** [comment]
For 48x48 dp is doubled as far as I can tell, so the 4dp padding becomes 8 pixels. Almost done resizing the 32 pixel icons, the 192 pixel ones will take more time so I will probably do those another day.

**Comment by conrad-heimbold** [comment]
I will re-create the resized icons almost from scratchm 
Scaling 32 up to 48 and 192 down to 48 will probably not look that good, if the shapes do not fit on the icon grid... The lowest-case svg icons should not be scaled.

**Comment by dkanada** [comment]
Scaling really shouldn't affect the svg files though, it would only be an issue with raster images like png files or something. The paths are saved with decimal places down to the thosandth place so resizing wont affect the icons unless we are converting between raster images and vector images. It's the same reason I thought the 192x192 icons wouldn't be so bad when exported as png files. Even though they are saved as 192 pixels wide, when they are downscaled to 48 pixels only the paths will be modified, and those are so precise it won't be that noticeable.

**Pull request merged**
