### PR TITLE
Add SVGs

### PR DESCRIPTION
**Pull request by ikocevski**
- ProtonMail - ch_protonmail_android_ch_protonmail_android_activities_SplashActivity

### CODE REVIEW

**Comment by conrad-heimbold** [comment]
@ikocevski congrats for your first commit / pull request ;)

**Comment by ikocevski** [comment]
Thanks! :)

**Comment by dkanada** [comment]
Hey there, thanks for the merge! I have been busy this past week moving to a new apartment across town but I will hopefully be done by Wednesday and then I will have more free time again, feel free to submit new icons whenever and I will get them added in the app.

**Comment by ikocevski** [comment]
Yeah, no problem. I'm glad if I'm of any use. This is like my first attempt to contribute for anything open-source but I should definitely stop using proprietary tools (Adobe Illustrator) :D

**Comment by dkanada** [comment]
Are you using Inkscape or Adobe Illustrator at the moment? Have you noticed any differences between the two causing you to prefer one over the other? I just started using Inkscape for this project, there are a few things I haven't found tools for yet like mirroring shapes across the page center and easily merging a path and stroke without using duplication.

**Comment by ikocevski** [comment]
I've been interested in making vector graphics before (making the crappy logo on my profile pic) and up until now I only knew about AI. I installed Inkscape just today to make the foobar2000 icon and I think it's even better, well at least for me as I really am a beginner at this. I didn't mind duplicating and flipping though, it's easier using the shortcuts (ctrl+d and h/v). What made things easier for me was the fine control over snapping to align. Choosing snapping to centers or paths with a single click was mind blowing. Anyway, I'm sure everything you can do with proprietary tools you can do it with its open-source alternative too and with my recent transition to everything FOSS I actually see that not only it's free but more than often this software is even better than it's proprietary counterpart.

**Comment by conrad-heimbold** [comment]
The only problem with FOSS  (at least in my experience) is, that sometimes the programs are much more **unstable** (at least with Inkscape) and not as "perfect". But fortunately, those problems are usually fixed very fast; because development is much more "fluid". 
See my problem with Inkscape, comment 3 at issue #9 .

**Comment by ikocevski** [comment]
Haven't had any stability issues personally. I got Arch with i3wm.

**Comment by conrad-heimbold** [comment]
@ikocevski: Are you always rebooting into Windows when using Adobe Illustrator? Or are you using a second laptop/pc with OS X? I'm just curious...

**Comment by ikocevski** [comment]
@conrad-heimbold I don't have my own computer but I can't install any Linux distro on the computers at home (a laptop and a PC both with Windows 10). People complained too much and I just bought myself a USB and installed arch on it. Whenever I want my OS I just plug my USB in and get on with my work. I'm kind of borrowing hardware ATM :D

**Pull request merged**
