### PR TITLE
improve existing svg files

### PR DESCRIPTION
**Pull request by conrad-heimbold**
... for android vector xml usage in the future.

### CODE REVIEW

**Comment by ikocevski** [comment]
Did you just edit these in a text editor or make them all over again?

**Comment by conrad-heimbold** [comment]
@ikocevski I only opened around 4 (syncthing, gplaystore, apktrack, cpuz) of them inside Inkscape; all other were done in a text editor.

**Comment by conrad-heimbold** [comment]
This pull request fixes **ALL** ..
- **fill-rule:evenodd** attributes, 
- **e-notation** numbers
- and **matrix/transform** elements

There should be **NO** left at all.

**Comment by ikocevski** [comment]
Good job!

**Comment by dkanada** [comment]
Thanks for making the changes, I'll be sure to watch for these issues in any future icons so we don't have to manually remove them again.

**Pull request merged**
